travis:
  secure:
    BINSTAR_TOKEN: LeTZc4yhyhv8CvjXcbKvOx3lle13cSit7NiAI8oWrshSJv11Z+zVu4eYZt8/E8TC6dHSpsJJ6akXRA3FG8567jIfss3NtIyEKKWmu2Ky3mXgF4FpMgNNEvhKSZJrfw0xk6Nu5vOnuaXL8A6bg29evnbF2K8goz6gMAlurPaB2CozPyMzQ9jCICaJfFbly8kbb3FYh79VWBaxELnIo6ihhNYLAj3ap0ZQP3Ka2Ott4ijaXjrgxquEmo6OF+11aaoThS/P6+Hu9lpXMrxYP1DFpNWxOodJLIOiF+D7rww//wv5Uk5I2bkDb2ZDxfteEesAe1j9ldBnCQmPki6+w5wLd8YqziTsVOl7NJBSg1CcldAPHZbUhp8jmh2JIjpKahseK52OUL9JUPTQkabGHY16YRNvKaXpy574z0IL+5rOlqfo4ljlJWbV+rY0z4ul9MOtp40JRU3hkLRT4tUzJv/j8EqihkzX7NWpqTG//mjKuilXmzymrInWqsUmYpsZbzwsUglJBBZw0pC1OHBcBKuu/y9y5Yuth4h+vbq/qRUGH2AbBqfAfCmDWG3WagnKMTkF9WZockH4mbhLsc6mQrJpDQT81G2gritpMI3eAKRHxxly5GBy2xPWY7v8N+muBzSC+o9F3HGU8Qi5d5HRiNl7lWpKEVv2o6yzZpO6QwBYNTQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
