travis:
  secure:
    BINSTAR_TOKEN: JGv4RCMfkobKb5727fFRTpqJ7pwo7uB6BWdJNpo8C6bYrmFKyp5XFVqfvVv6glYMYn1Q0AWqzPxY9MUIiJyjQkY2BwfSagtYNOa0siTfV/kwXoHF1cxHrn7I1HqNSjeLFkm58CF0NGH2y/K/s3ZBxFEPXedcKUdHOdGMFkg6yMyLxfoXJX/wLlkO8mfTMe/Agt1JwjuSLxGCtGrReHaudNC2fYjXyho02mHM4X33ZxPbzX/V4Ch/s5KTvUrGdiXimVd3f3RX8nNL3cQP5ryH5Kc5Mvzchw90RrrPoChzujOmwT6xj/YFrgrF6a2oxVZNXCWTjHyUrTvG9xY3rJu+mZKIGA1ER208zRRNCZU5ZGNvwXKGIxymVAgL9gwKnkW10CMnPNf3ldS29A/Z+y+bZNxAu3KC0noMyJ1cLlrxPxvw+WqRb3M3WaTpZq6lk7JEfPuhkIVaCaBiHjaVndmq30cBO3dTJ6A1EVFXo2fyaRScdiTvCzZ0rtQyHr7s4uD8cOTQhk0HxVPopJ3R+qUX9ci2+5R2/Fi02nftE4rIbE27KiJq95qAMrq/R64cRFl4wT/izZ/4exfLFLNrn3RPEbk7mGUCVro5qPALvAX6qZes3M64G9QyPeW1dnNAvuMDuVkM9hsFOcQbGkDcrZ8NgFvIwGKSsLVPcAWk6p9TN7U=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
